#!/bin/bash

prettier_cmd="npx prettier --write --print-width 100 --tab-width 2 --use-tabs false"

files=$(git diff --name-only --cached '*.js' '*.jsx' '*.scss' '*.css' '*.html')
[ -z "$files" ] && exit 0

echo "Running Prettier on staged files..."
$prettier_cmd $files

if [ $? -ne 0 ]; then
    echo "Prettier failed to run. Aborting commit."
    exit 1
fi

git add $files

echo "Prettier formatting applied to staged files."
exit 0